name: dikt
description: dikt - bottom-up offline dictionary
publish_to: 'none'

version: 2.2.1+32

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  provider: ^6.0.1
  path_provider: ^2.0.1
  shared_preferences:
  flutter_html:
    path: ./plugins/flutter_html-2.0.0
  hive: ^2.0.4
  flutter_sticky_header: ^0.6.3 # fixing at 0.6.1, 0.6.2 breaked dictionary selection via drop down list at _FuturedArticleBodyState
  reorderables: # added onDragging event handler to allow deletion of dics by dragging them on a dedicated elemtn
    path: ./plugins/reorderables-0.4.1/
  file_picker: ^6.1.1
  i18n_extension: ^10.0.1
  firebase_core: ^2.12.0
  page_transition: ^2.0.2
  file_selector_platform_interface: any
  file_selector_linux: any
  file_selector_macos: any
  file_selector_windows: any
  flutter_hooks: ^0.20.0
  superellipse_shape: ^0.2.0
  ikvpack:
    git: https://github.com/maxim-saplin/ikvpack
    #path: '../ikvpack'
  package_info_plus: ^4.0.0  
  after_layout: ^1.1.0  
  path: ^1.8.1
  js:
  archive:
  isolate_pool_2:
  multi_split_view: ^2.2.0
  flutter_styled_toast: ^2.1.3
  ambilytics: ^1.0.1
  receive_intent:
  # action_process_text:
  #   path: ../action_process_text


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  hive_generator: 
  build_runner: 
  flutter_launcher_icons:
  flutter_native_splash:
  test: ^1.24.0
  flutter_lints:
  golden_toolkit: # Solving problem with not rendered fonts

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  image: assets/splash.png
  color: "000000"


flutter:
  uses-material-design: true

  assets:
    - assets/dictionaries/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Montserrat-Italic.ttf
          style: italic
    - family: Tinos
      fonts:
        - asset: assets/Tinos-Regular.ttf
        - asset: assets/Tinos-Bold.ttf
          weight: 700
        - asset: assets/Tinos-Italic.ttf
          style: italic