name: dikt
description: dikt - bottom-up offline dictionary.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+5

environment:
  sdk: ">=2.11.0-213.0.dev <2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  provider: ^4.0.2
  shared_preferences: ^0.5.12+4
  flutter_html: ^1.0.2
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  sprintf: ^4.0.0
  archive: ^2.0.13
  flutter_sticky_header: ^0.4.2
  reorderables: ^0.3.2
  double_back_to_close: ^1.0.2+mit
  fluttertoast: 7.0.1
  file_picker: ^2.0.0
  i18n_extension: ^1.4.2
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  page_transition: ^1.1.6
  file_chooser:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/file_chooser
      ref: 5b3b930da18244ecf2a7140a0e33a9892273797c
  dictionary_bundler:
  flutter_hooks: ^0.14.1-nullsafety

dependency_overrides:
  flutter_svg: 0.18.0 #Flutter 1.20 and flutter_html issue
  path: 1.6.4
  hive: # custom version remove box key assertion to be ASCII string not greater than 255 chars
    path: ./plugins/hive-1.4.1+1/
  reorderables:
    path: ./plugins/reorderables-0.3.2/
  flutter_html:
    path: ./plugins/flutter_html-1.0.2
  dictionary_bundler:
    path: ./dictionary_bundler/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  hive_not_tuned: # used for benchamrking against performance tuned hive above
    path: ./plugins/hive-not-tuned-1.4.1+1/
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.0
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  image: assets/splash.png
  color: "000000"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/dictionaries/
  #  - assets/dictionaries2/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Montserrat-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
