name: Build Release Binaries (ARM)
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted   
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 19.x
        cache: 'gradle' 
    - uses: subosito/flutter-action@v2
      with:
         channel: 'stable'
         architecture: arm64
         cache: true
         cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
    - name: Build macOS
      run: flutter build macos
      working-directory: ./
    - name: Compress dikt.app
      run: |
        zip -r ./build/dikt-macOS-ARM64.zip ./build/macos/Build/Products/Release/dikt.app/
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dikt-macOS-ARM64.zip
        path: ./build/dikt-macOS-ARM64.zip
