name: Build Release Binaries
on: [workflow_dispatch]
jobs:
  build:
    runs-on: macOS ARM64   
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle' 
    - uses: subosito/flutter-action@v2
      with:
         channel: 'stable'
         architecture: arm64
         cache: true
         cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
    - name: Build macOS
      run: flutter build macos
      working-directory: ./
    - uses: actions/upload-artifact@v3
      with:
        name: dikt.app
        path: ./build/macos/Build/Products/Release/dikt.app
