name: dikt

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest     
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle' 
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        cache: true
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
#     - name: Enable Web
#       run: flutter config --enable-web
#       working-directory: ./
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
    - name: Build macOS
      run: flutter build macos
      working-directory: ./

