name: Build Release Binaries (ARM)
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted   
    steps:
    - uses: actions/checkout@v1
# No need for self-hosted runnder
#     - uses: actions/setup-java@v3
#       with:
#         distribution: zulu
#         java-version: 19.x
#         cache: 'gradle' 
    - uses: subosito/flutter-action@v2
      with:
         channel: 'stable'
         architecture: arm64
         cache: true
         cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
    - name: Build macOS
      run: flutter build macos
      working-directory: ./
    - name: Extract version from pubspec.yaml
    # sed -n 's/^version: *//p' pubspec.yaml     
      run: |
        echo "VERSION=$(sed -n 's/^version: *//p' pubspec.yaml)" >> $GITHUB_OUTPUT
      id: app_version
      
    - name: Compress dikt.app
      working-directory: ./build/macos/Build/Products/Release/
      run: |
        zip -r -D -y ./build/dikt-macOS-ARM64.zip dikt.app
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: dikt-${{ steps.app_version.outputs.VERSION }}(macOS-ARM64).zip
        path: ./build/dikt-macOS-ARM64.zip
