name: Build macOS (ARM/self-hosted)
on: [workflow_dispatch, workflow_call]
jobs:
  build:
    runs-on: self-hosted   
    steps:
    - uses: actions/checkout@v1
# No need for self-hosted runnder
#     - uses: actions/setup-java@v3
#       with:
#         distribution: zulu
#         java-version: 19.x
#         cache: 'gradle' 
#    - uses: subosito/flutter-action@v2
#      with:
#         channel: 'stable'
#         architecture: arm64
#         cache: true
#         cache-key: 'flutter-:os:-:channel:-:version:-:arch:'
#    - name: Flutter Doctor
#      run: flutter doctor
#    - name: Upgrades flutter
#      run: flutter upgrade
    - name: Install dependencies
      run: flutter packages get
    - name: Run tests
      run: flutter test --coverage
    - name: Build macOS
      run: flutter build macos
    - name: Extract version from pubspec.yaml
    # sed -n 's/^version: *//p' pubspec.yaml     
      run: |
        echo "VERSION=$(sed -n 's/^version: *//p' pubspec.yaml)" >> $GITHUB_ENV
      id: app_version
      
    - name: Compress and package the artifact (macOS)
      run: |
        cd build/macos/Build/Products/Release/
        zip -r -D -y dikt-macOS-arm64-${{ env.VERSION }}.zip dikt.app
        mv dikt-macOS-arm64-${{ env.VERSION }}.zip ../../../../dikt-macOS-arm64-${{ env.VERSION }}.zip
        
    - name: Upload Artifact (macOS)
      uses: actions/upload-artifact@v3
      with:
        name: dikt-macOS-arm64-${{ env.VERSION }}
        path: build/dikt-macOS-arm64-${{ env.VERSION }}.zip
        if-no-files-found: error
