name: Build and Release (Desktop and Mobile)

on: [workflow_dispatch]

jobs:
  self-hosted:
    name: Run self-hosted
    uses: ./.github/workflows/build_macos_arm_sh.yaml
  GH-hosted:
    name: Run GH-hosted
    uses: ./.github/workflows/build_wlma_binaries_ghh.yaml
