name: Build and Publish Web

on:
  schedule:
    - cron: '0 0 * * *' # Run once a day at 00:00 UTC
  push:
    branches: [main] # only if there're commits

jobs:
  build:
    runs-on: macos-latest     
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: "12.x"
        cache: 'gradle' 
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
        cache: true
    - name: Flutter Doctor
      run: flutter doctor
      working-directory: ./
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
#     - name: Enable Web
#       run: flutter config --enable-web
#       working-directory: ./
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
#     - name: Setup tmate session
#       uses: mxschmitt/action-tmate@v3
#       timeout-minutes: 15
#     - name: Install dependencies
#       run: |
#         flutter clean
#         flutter pub upgrade
#       working-directory: ./
    - name: Build Web
      run: flutter build web
      working-directory: ./
    - name: Fix PWA
      run: sed -i'.js' -e 's+"/"+""+g' flutter_service_worker.js #https://github.com/flutter/flutter/issues/68449
      working-directory: ./build/web
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./build/web
