name: dikt

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest     
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.0-12.0.pre' # you can use 1.12
        channel: 'dev'
    - name: Upgrades flutter
      run: flutter upgrade
      working-directory: ./
    - name: Enable Web
      run: flutter config --enable-web
      working-directory: ./
    - name: Install dependencies
      run: flutter packages get
      working-directory: ./
    - name: Build Web
      run: flutter build web
      working-directory: ./
    - name: Deploy
      run: |
        cd /build/web
        git init
        git config user.name  "CI"
        git config user.email "flutter-ci@github.com"
        git remote add secure-origin https://${{ secrets.ACCESS_TOKEN }}@github.com/[maxim-saplin]/[dikt].git
        git checkout -b gh-pages
        git add .
        git commit -m "Updated dikt"
        git push --force secure-origin gh-pages
